# .github/workflows/tests.yml
name: Run Pytest

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      MY_VARIABLE: "my_value"

    steps:
      - name: Print variable
        run: echo "The value is ${{ env.MY_VARIABLE }}"
        
      - name: Checkout репозиторий
        uses: actions/checkout@v3

      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Запуск тестов
        run: pytest

      - name: Генерация HTML-отчёта
        run: pytest --html=report.html

      - name: Сохранение артефакта
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: report.html
